### ISSUE TITLE
es.xiaoleilu.com 打不开了

### ISSUE THREAD

**Issue by ikool2018** [looly/elasticsearch-definitive-guide-cn#109]
es.xiaoleilu.com 打不开了

**Comment by looly** [comment]
这个域名转向了Gitbook，可能由于一些原因国内访问比较缓慢。你可以看 http://wiki.jikexueyuan.com/project/elasticsearch-definitive-guide-cn/

**Comment by occultskyrong** [comment]
@looly 
网站GG了，
```
Error 1001 Ray ID: 311615d2122a3367 • 2016-12-15 01:22:33 UTC
DNS resolution error
```

**Comment by mozhuwanjieDEV** [comment]
What happened?
You've requested a page on a website (es.xiaoleilu.com) that is on the CloudFlare network. CloudFlare is currently unable to resolve your requested domain (es.xiaoleilu.com). There are two potential causes of this:
Most likely: if the owner just signed up for CloudFlare it can take a few minutes for the website's information to be distributed to our global network.
Less likely: something is wrong with this site's configuration. Usually this happens when accounts have been signed up with a partner organization (e.g., a hosting provider) and the provider's DNS fails.

**Comment by occultskyrong** [comment]
可以了。。。。

**Comment by looly** [comment]
已修复
